// GENERATED by scripts/gen-body-types.ts from MezzoSopranoClef clients/schema.json. Do not edit.
// Source protocol 2, server "MezzoSopranoClef".

export const CLEF_PROTOCOL = 2 as const;

/** Every command the body knows, with its typed args. Keys are the wire `cmd` names. */
export interface ClefCommands {
  "ping": Record<never, never>;
  "help": Record<never, never>;
  "schema": Record<never, never>;
  "stats": Record<never, never>;
  "optimize": {
    "sound"?: boolean;
  };
  "subscribe": {
    "events"?: string[];
  };
  "unsubscribe": Record<never, never>;
  "events": Record<never, never>;
  "status": Record<never, never>;
  "auth.status": Record<never, never>;
  "control.rotateToken": Record<never, never>;
  "connect": {
    "host": string;
    "port"?: number; // default 25565
  };
  "disconnect": Record<never, never>;
  "chat": {
    "message": string;
  };
  "chatHistory": {
    "limit"?: number; // default 50
  };
  "whisper": {
    "player": string;
    "text": string;
  };
  "batch": {
    "commands": unknown;
    "continueOnError"?: boolean; // default false
  };
  "look": {
    "yaw"?: number;
    "pitch"?: number;
  };
  "lookAt": {
    "x"?: number;
    "y"?: number;
    "z"?: number;
    "entityId"?: number;
  };
  "players": Record<never, never>;
  "headless": {
    "enabled"?: boolean;
  };
  "screenshot": {
    "x"?: number;
    "y"?: number;
    "z"?: number;
    "yaw"?: number;
    "pitch"?: number;
    "width"?: number;
    "height"?: number;
    "fov"?: number;
    "mode"?: string; // default normal
    "centerX"?: number;
    "centerZ"?: number;
    "radius"?: number; // default 32
    "annotate"?: boolean; // default false
  };
  "registry": {
    "kinds"?: string[];
    "tags"?: boolean; // default false
  };
  "goto": {
    "x": number;
    "z": number;
    "y"?: number;
    "reach"?: number; // default 1
  };
  "nav.check": {
    "x": number;
    "y": number;
    "z": number;
    "reach"?: number; // default 1
    "maxNodes"?: number;
  };
  "baritone": {
    "command": string;
    "collectMs"?: number; // default 250
  };
  "nav.stop": Record<never, never>;
  "nav.status": Record<never, never>;
  "move": {
    "forward"?: boolean;
    "backward"?: boolean;
    "left"?: boolean;
    "right"?: boolean;
    "jump"?: boolean;
    "sneak"?: boolean;
    "sprint"?: boolean;
    "durationMs"?: number;
  };
  "stopMove": Record<never, never>;
  "mine": {
    "x": number;
    "y": number;
    "z": number;
    "face"?: string; // default up
    "wait"?: boolean; // default false
  };
  "stopMine": Record<never, never>;
  "breakBlock": {
    "x": number;
    "y": number;
    "z": number;
  };
  "place": {
    "x": number;
    "y": number;
    "z": number;
    "face"?: string; // default up
    "item"?: string;
    "confirm"?: boolean; // default true
  };
  "use": {
    "hand"?: string; // default main
  };
  "attack": {
    "entityId"?: number;
  };
  "setSlot": {
    "slot": number;
  };
  "dropItem": {
    "all"?: boolean;
  };
  "inventory": Record<never, never>;
  "entities": {
    "radius"?: number; // default 16
    "kinds"?: string[];
  };
  "blockAt": {
    "x": number;
    "y": number;
    "z": number;
  };
  "findBlocks": {
    "ids": string[];
    "radius"?: number; // default 32
    "max"?: number; // default 32
    "sort"?: string; // default nearest
  };
  "blocksIn": {
    "minX": number;
    "minY": number;
    "minZ": number;
    "maxX": number;
    "maxY": number;
    "maxZ": number;
    "palette"?: boolean; // default true
  };
  "target": {
    "maxDistance"?: number; // default 4.5
    "fluids"?: boolean; // default false
  };
  "interactEntity": {
    "entityId": number;
    "hand"?: string; // default main
  };
  "swapHands": Record<never, never>;
  "pickBlock": {
    "x": number;
    "y": number;
    "z": number;
    "nbt"?: boolean;
  };
  "useHold": {
    "ticks"?: number; // default 40
  };
  "useRelease": Record<never, never>;
  "eat": {
    "ticks"?: number; // default 40
  };
  "respawn": Record<never, never>;
  "craft": {
    "item": string;
    "count"?: number; // default 1
    "all"?: boolean; // default false
  };
  "recipes": {
    "item": string;
  };
  "craftable": Record<never, never>;
  "container": Record<never, never>;
  "clickSlot": {
    "slot": number;
    "button"?: number; // default 0
    "mode"?: string; // default pickup
  };
  "closeScreen": Record<never, never>;
  "selectTrade": {
    "index": number;
  };
  "screen": Record<never, never>;
  "clickButton": {
    "index": number;
  };
  "setText": {
    "index": number;
    "text"?: string; // default 
  };
  "serverui": Record<never, never>;
  "findItem": {
    "item": string;
  };
  "equip": {
    "item": string;
  };
  "moveToHotbar": {
    "item": string;
    "slot"?: number;
  };
  "deposit": {
    "item": string;
  };
  "withdraw": {
    "item": string;
  };
  "dropStack": {
    "item": string;
  };
}

export type ClefCommandName = keyof ClefCommands;

/** Every event the body can push, with its data fields. */
export interface ClefEvents {
  /** sent once on connect, before auth */
  "welcome": {
    "server": string;
    "protocol": number;
    "requiresAuth": boolean;
  };
  /** a chat, system, whisper, team or action-bar message arrived; 'raw' is the JSON component, 'kind' is chat|system|whisper|team|actionbar */
  "chat": {
    "text": string;
    "sender"?: string;
    "kind": string;
    "raw"?: string;
  };
  /** health or hunger changed */
  "health": {
    "health": number;
    "food": number;
  };
  /** the bot took damage */
  "damage": {
    "amount": number;
    "health": number;
  };
  /** the bot died */
  "death": Record<never, never>;
  /** the bot respawned */
  "respawn": Record<never, never>;
  /** a player entered the tab list */
  "join": {
    "name": string;
  };
  /** a player left the tab list */
  "leave": {
    "name": string;
  };
  /** the bot connected to a server */
  "connected": Record<never, never>;
  /** the bot left a server */
  "disconnected": Record<never, never>;
  /** throttled state snapshot (~1/s) */
  "tick": {
    "x": number;
    "y": number;
    "z": number;
    "yaw": number;
    "pitch": number;
    "health": number;
    "food": number;
    "dimension": string;
  };
  /** a container/screen opened. 'screen' is a stable readable name (title|connect|disconnected|death|downloading|message|inventory|crafting|furnace|anvil|enchanting|merchant|sign|book|container|other); 'screenClass' is the raw class, which is obfuscated outside a dev run */
  "screenOpen": {
    "screen": string;
    "screenClass": string;
  };
  /** the open screen closed */
  "screenClose": {
    "screen": string;
    "screenClass": string;
  };
  /** an entity appeared nearby (within 24 blocks) */
  "entitySpawn": {
    "id": number;
    "type": string;
    "x": number;
    "y": number;
    "z": number;
  };
  /** a nearby entity left */
  "entityRemove": {
    "id": number;
  };
  /** an entity within events.packetRadius took damage — including us; 'attacker' is the entity id that dealt it, which is what self-defence needs */
  "entityHurt": {
    "id": number;
    "type": string;
    "self": boolean;
    "health": number;
    "source"?: string;
    "attacker"?: number;
    "attackerType"?: string;
  };
  /** the bot picked an item up */
  "itemPickup": {
    "item": string;
    "count": number;
  };
  /** inventory slots changed this tick; fetch values with the inventory command */
  "inventory": {
    "changed": number[];
  };
  /** a block changed within events.blockUpdateRadius of the bot */
  "blockUpdate": {
    "x": number;
    "y": number;
    "z": number;
    "from": string;
    "to": string;
  };
  /** an explosion went off within events.packetRadius. 1.21.8's packet carries no blast power, so 'knockback' (the impulse applied to us) is the only magnitude */
  "explosion": {
    "x": number;
    "y": number;
    "z": number;
    "distance": number;
    "knockback"?: unknown;
  };
  /** weather changed: clear | rain | thunder */
  "weather": {
    "kind": string;
  };
  /** the day phase changed: dawn | day | dusk | night */
  "time": {
    "phase": string;
    "time": number;
    "day": number;
  };
  /** the bot fell asleep (ok:true) or a bed was refused (ok:false, reason from the server's block.minecraft.bed.* message) */
  "sleep": {
    "ok": boolean;
    "reason"?: string;
    "key"?: string;
    "x"?: number;
    "y"?: number;
    "z"?: number;
  };
  /** the title, subtitle or action bar text changed */
  "title": {
    "title": string;
    "subtitle": string;
    "actionBar": string;
  };
  /** a mine request finished; reason is cant_break | cancelled | replaced | not_in_world */
  "mineDone": {
    "x": number;
    "y": number;
    "z": number;
    "broken": boolean;
    "reason"?: string;
    "detail"?: string;
    "ticks": number;
  };
  /** the bot reached its goto goal */
  "nav.done": {
    "x": number;
    "y"?: number;
    "z": number;
    "reach": number;
  };
  /** the goal is over and was NOT reached. Always terminal — no nav.done can follow for the same goal. reason is a terminal Baritone PathEvent (CALC_FAILED, CANCELED) or CANCELLED | NO_PATH | REPLACED */
  "nav.failed": {
    "x": number;
    "y"?: number;
    "z": number;
    "reach": number;
    "reason": string;
    "terminal": boolean;
  };
  /** Baritone is still working on the goal and something notable happened (NEXT_CALC_FAILED, SPLICING_ONTO_NEXT_EARLY, ...). Informational: the goal is still live, so do NOT treat this as a failure */
  "nav.progress": {
    "x": number;
    "y"?: number;
    "z": number;
    "reach": number;
    "event": string;
  };
  /** a line Baritone would have printed to the chat HUD — find results, eta, 'No known locations of ...', build progress, missing materials */
  "baritone.log": {
    "text": string;
  };
  /** device-code login: show this to the user (always delivered) */
  "auth.prompt": {
    "verificationUri": string;
    "userCode": string;
  };
  /** login succeeded (always delivered) */
  "auth.ok": Record<never, never>;
  /** login failed (always delivered) */
  "auth.error": {
    "error"?: string;
  };
}

export type ClefEventName = keyof ClefEvents;

export type ClefErrorCode =
  | "INVALID_JSON"
  | "MISSING_CMD"
  | "UNKNOWN_COMMAND"
  | "UNAUTHORIZED"
  | "BAD_TOKEN"
  | "BAD_ARGS"
  | "NOT_IN_WORLD"
  | "NOT_CONNECTED"
  | "NOT_FOUND"
  | "RATE_LIMIT"
  | "COMMAND_FAILED";

/** Command names present in the schema this file was generated from (for capability diffs). */
export const CLEF_KNOWN_COMMANDS: readonly string[] = ["ping","help","schema","stats","optimize","subscribe","unsubscribe","events","status","auth.status","control.rotateToken","connect","disconnect","chat","chatHistory","whisper","batch","look","lookAt","players","headless","screenshot","registry","goto","nav.check","baritone","nav.stop","nav.status","move","stopMove","mine","stopMine","breakBlock","place","use","attack","setSlot","dropItem","inventory","entities","blockAt","findBlocks","blocksIn","target","interactEntity","swapHands","pickBlock","useHold","useRelease","eat","respawn","craft","recipes","craftable","container","clickSlot","closeScreen","selectTrade","screen","clickButton","setText","serverui","findItem","equip","moveToHotbar","deposit","withdraw","dropStack"];
