// Generates src/body/schema.gen.ts from MezzoSopranoClef's clients/schema.json.
//
// The schema is the body's authoritative contract (commands + typed args, events + fields, error
// codes, protocol version). We commit the generated file so Golem builds without the sibling repo,
// and re-run this whenever Clef's API changes:  npm run gen:body  (or CLEF_SCHEMA=/path/to/schema.json).
//
// Result types are NOT in the schema (Clef only types args), so the hand-written result shapes for
// the commands Golem relies on live in src/body/results.ts.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = process.env.CLEF_SCHEMA ?? resolve(here, "../../MezzoSopranoClef/clients/schema.json");
const outPath = resolve(here, "../src/body/schema.gen.ts");

type Arg = { name: string; type: string; required?: boolean; default?: string };
type Cmd = { name: string; description?: string; args?: Arg[]; readOnly?: boolean };
type Ev = { name: string; description?: string; fields?: Arg[] };
type Schema = { protocol: number; server: string; commands: Cmd[]; events: Ev[]; errors: { code: string; meaning: string }[] };

const schema: Schema = JSON.parse(readFileSync(schemaPath, "utf8"));

/** Clef arg types -> TS types. Anything unknown becomes `unknown` so the build still passes. */
function tsType(t: string): string {
  switch (t) {
    case "int": case "float": case "double": case "long": return "number";
    case "bool": return "boolean";
    case "string": return "string";
    case "string[]": return "string[]";
    case "int[]": return "number[]";
    case "object": return "Record<string, unknown>";
    default: return "unknown";
  }
}

function argsInterface(args: Arg[] | undefined): string {
  if (!args || args.length === 0) return "Record<never, never>";
  const lines = args.map((a) => {
    const opt = a.required ? "" : "?";
    const def = a.default !== undefined ? ` // default ${a.default}` : "";
    return `    ${JSON.stringify(a.name)}${opt}: ${tsType(a.type)};${def}`;
  });
  return `{\n${lines.join("\n")}\n  }`;
}

const out: string[] = [];
out.push("// GENERATED by scripts/gen-body-types.ts from MezzoSopranoClef clients/schema.json. Do not edit.");
out.push(`// Source protocol ${schema.protocol}, server ${JSON.stringify(schema.server)}.`);
out.push("");
out.push(`export const CLEF_PROTOCOL = ${schema.protocol} as const;`);
out.push("");
out.push("/** Every command the body knows, with its typed args. Keys are the wire `cmd` names. */");
out.push("export interface ClefCommands {");
for (const c of schema.commands) {
  if (c.description) out.push(`  /** ${c.description.replace(/\*\//g, "* /")} */`);
  out.push(`  ${JSON.stringify(c.name)}: ${argsInterface(c.args)};`);
}
out.push("}");
out.push("");
out.push("export type ClefCommandName = keyof ClefCommands;");
out.push("");
out.push("/** Every event the body can push, with its data fields. */");
out.push("export interface ClefEvents {");
for (const e of schema.events) {
  if (e.description) out.push(`  /** ${e.description.replace(/\*\//g, "* /")} */`);
  out.push(`  ${JSON.stringify(e.name)}: ${argsInterface(e.fields)};`);
}
out.push("}");
out.push("");
out.push("export type ClefEventName = keyof ClefEvents;");
out.push("");
out.push("export type ClefErrorCode =");
out.push(schema.errors.map((e) => `  | ${JSON.stringify(e.code)}`).join("\n") + ";");
out.push("");
out.push("/** Command names present in the schema this file was generated from (for capability diffs). */");
out.push(`export const CLEF_KNOWN_COMMANDS: readonly string[] = ${JSON.stringify(schema.commands.map((c) => c.name))};`);
out.push("");

writeFileSync(outPath, out.join("\n"));
console.log(`wrote ${outPath}: ${schema.commands.length} commands, ${schema.events.length} events, ${schema.errors.length} error codes`);
