// Regenerates the tool table in docs/MCP-TOOLS.md from the registry, so the doc can't drift.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { ALL_TOOLS as TOOLS } from "../src/mcp/tools.ts";

const here = dirname(fileURLToPath(import.meta.url));
const docPath = resolve(here, "../docs/MCP-TOOLS.md");
const groupOf = (n: string): string =>
  ["status", "look_around", "see", "map", "find_blocks", "find_entities", "block_at", "inventory", "container", "craftable", "recipe", "players", "chat_history", "target"].includes(n) ? "Perception"
  : ["goto", "goto_nearest", "goto_player", "follow", "stop", "look_at", "explore", "surface"].includes(n) ? "Movement"
  : ["say", "whisper", "inbox"].includes(n) ? "Comms"
  : n.startsWith("shem_") ? "Scripts (Shem)"
  : ["remember", "reflexes", "reflex_set", "goal_set", "goal_clear", "met"].includes(n) ? "Memory, reflexes, goals, kill switch"
  : "Actions";
const groups = new Map<string, string[]>();
for (const t of TOOLS) {
  const g = groupOf(t.name);
  if (!groups.has(g)) groups.set(g, []);
  groups.get(g)!.push(`| \`${t.name}\` | ${Object.keys(t.input).join(", ")} | ${t.description} |`);
}
let table = "";
for (const [g, rows] of groups) table += `\n### ${g}\n\n| Tool | Args | What it does |\n|---|---|---|\n${rows.join("\n")}\n`;
// Explicit markers, because the obvious end-of-region search does not work here: the generated
// table contains "### Scripts (Shem)" as a group heading, and `indexOf("## Scripts")` matches
// inside it. That put the tail marker *within* the generated region, so every run kept its own
// output and appended a fresh copy - eleven duplicate sections had accumulated in the committed
// doc before anyone read past the tables.
const BEGIN = "<!-- BEGIN generated tools: scripts/gen-tool-docs.ts -->";
const END = "<!-- END generated tools -->";
let s = readFileSync(docPath, "utf8");
const start = s.indexOf(BEGIN);
const end = s.indexOf(END);
if (start < 0 || end < 0 || end < start) {
  throw new Error(`docs/MCP-TOOLS.md is missing the ${BEGIN} / ${END} markers; add them around the tool tables`);
}
s = s.slice(0, start) + BEGIN + `\n## Registered tools (${TOOLS.length}, generated by scripts/gen-tool-docs.ts)\n` + table + "\n" + s.slice(end);
writeFileSync(docPath, s);
console.log(`docs/MCP-TOOLS.md: ${TOOLS.length} tools in ${groups.size} groups`);
