// Regenerates the tool table in docs/MCP-TOOLS.md from the registry, so the doc can't drift.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { ALL_TOOLS as TOOLS } from "../src/mcp/tools.ts";

const here = dirname(fileURLToPath(import.meta.url));
const docPath = resolve(here, "../docs/MCP-TOOLS.md");
const groupOf = (n: string): string =>
  ["status", "look_around", "see", "map", "find_blocks", "find_entities", "block_at", "inventory", "container", "craftable", "recipe", "players", "chat_history", "target"].includes(n) ? "Perception"
  : ["goto", "goto_nearest", "goto_player", "follow", "stop", "look_at", "explore", "surface"].includes(n) ? "Movement"
  : ["say", "whisper", "inbox"].includes(n) ? "Comms"
  : n.startsWith("shem_") ? "Scripts (Shem)"
  : ["remember", "reflexes", "reflex_set", "goal_set", "goal_clear", "met"].includes(n) ? "Memory, reflexes, goals, kill switch"
  : "Actions";
const groups = new Map<string, string[]>();
for (const t of TOOLS) {
  const g = groupOf(t.name);
  if (!groups.has(g)) groups.set(g, []);
  groups.get(g)!.push(`| \`${t.name}\` | ${Object.keys(t.input).join(", ")} | ${t.description} |`);
}
let table = "";
for (const [g, rows] of groups) table += `\n### ${g}\n\n| Tool | Args | What it does |\n|---|---|---|\n${rows.join("\n")}\n`;
let s = readFileSync(docPath, "utf8");
const start = s.indexOf("## Registered tools");
const end = s.indexOf("## Scripts");
const head = start >= 0 ? s.slice(0, start) : s.slice(0, s.indexOf("## Perception"));
s = head + `## Registered tools (${TOOLS.length}, generated by scripts/gen-tool-docs.ts)\n` + table + "\n" + s.slice(end);
writeFileSync(docPath, s);
console.log(`docs/MCP-TOOLS.md: ${TOOLS.length} tools in ${groups.size} groups`);
